### ISSUE TITLE
Kanban board set up 

### ISSUE THREAD

**Issue by ghost** [zainsadaqat/recipe-app#15]
### Hello there! we are a team of two people working on **ROR group project**

To check our project click here [Kanban board](https://github.com/zainsadaqat/recipe-app/projects/1)

### Team members:
Team members are listed below:

1. @zainsadaqat 
2. @Hope1226  

_Feel free to leave us any suggestions or changes! Cheers!!_

**Comment by elisha2kyakpo1** [comment]
Hi team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

I wish you the best of luck 👍

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
